# Generated by Django 2.2.12 on 2020-04-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_kategoriya'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kategoriya',
            field=models.ManyToManyField(help_text='Вибери категорію статті', to='blog.Kategoriya'),
        ),
    ]
